### ISSUE TITLE
Show mob health value in it's nametag, next to his name and level

### ISSUE THREAD

**Issue by Sceat** [aresrpg/aresrpg#135] opened 2021-02-19 01:58 UTC

**Comment by DeltaEvo** [comment] 2021-02-19 07:06
Is this a duplicate of #104 ?

**Comment by Sceat** [comment] 2021-02-19 07:08
nop, the name above the mob

**Comment by DeltaEvo** [comment] 2021-02-26 15:27
This was not in the v1 do we really want to add that @Sceat ?

**Comment by Sceat** [comment] 2021-02-26 15:28
It was a numeric value

**Comment by DeltaEvo** [comment] 2021-02-26 15:28
It was for all the mobs ?

**Comment by Sceat** [comment] 2021-02-26 15:32
![image](https://user-images.githubusercontent.com/11330271/109320288-23e72600-7850-11eb-8465-deff98b5c67f.png)

**Comment by Sceat** [comment] 2021-02-26 15:32
We may had to attack them first to see the health

**Closed** 2022-01-19 20:05 UTC
Labels: feature
